export const data = [
    {
      id: 1,
      title: "Amala",
      category: "Breakfast",
      price: "N500",
      img: "https://harvestlagos.com/wp-content/uploads/2021/04/amala.jpg",
      desc: `Amala is a local indigenous Yoruba food, native to the Yoruba ethnic group.`,
    },
    {
      id: 2,
      title: "Spaghetti",
      category: "Lunch",
      price: "N950",
      img: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
      desc: `Spaghetti is a long, thin, solid, cylindrical pasta. It is a staple food of traditional Italian cuisine. `,
    },
    {
      id: 3,
      title: "rasperry milkshake",
      category: "Shakes",
      price: "N1250",
      img: "https://images.unsplash.com/photo-1472555794301-77353b152fb7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=437&q=80",
      desc: `A raspberry milkshake is a simple blended drink made with raspberries, vanilla ice cream, and milk.`,
    },
    {
      id: 4,
      title: "Jollof Rice",
      category: "Breakfast",
      price: "N850",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Jollof_Rice_with_Stew.jpg/330px-Jollof_Rice_with_Stew.jpg",
      desc: `Jollof rice, is a rice dish from West Africa. The dish is typically made with long-grain rice, tomatoes, onions, spices, vegetables and meat in a single pot, although its ingredients and preparation methods vary across different regions.`,
    },
    {
      id: 5,
      title: "Dodo",
      category: "Lunch",
      price: "N250",
      img: "https://static01.nyt.com/images/2019/06/26/dining/24Nigerianrex6/24Nigerianrex6-articleLarge.jpg",
      desc: `Fried, grilled, boiled, dehydrated and pulverized, sweet or savory, plantains are a staple of Nigerian cuisine.  `,
    },
    {
      id: 6,
      title: "Vanilla shake",
      category: "Shakes",
      price: "N1150",
      img: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4473406.jpg&w=595&h=595&c=sc&poi=face&q=60",
      desc: `A vanilla milkshake recipe that's very easy to make. Add chocolate, berries, peaches, or whatever you like.`,
    },
    {
      id: 7,
      title: "Beans and bread",
      category: "Breakfast",
      price: "N350",
      img: "https://allnigerianfoods.com/wp-content/uploads/Ewa-agoyin.jpg",
      desc: `Another Nigerian food that is awesome and simply amazing and affordable is bread and beans.
  It is cheap and lovely. `,
    },
    {
      id: 8,
      title: "Fried egg",
      category: "Lunch",
      price: "N400",
      img: "https://allnigerianfoods.com/wp-content/uploads/fried-eggs-1.jpg",
      desc: `Fried eggs are one of the easy lunch ideas from Nigeria. You could serve with bread, yams or even noodles.`,
    },
    {
      id: 9,
      title: "Banana shakes",
      category: "Shakes",
      price: "N1000",
      img: "https://images.unsplash.com/photo-1542444592-e6880e286bb9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=361&q=80",
      desc: `An easy banana shake you can make in minutes, with creamy vanilla ice cream, a pinch of cinnamon and a swizzle of whipped cream`,
    },
  ];